version: '3'
services:
  hub:
    image: selenium/hub:4.10
    ports:
    - 4444:4444
  chrome:
    image: selenium/node-chrome:4.10
    shm_size: '2g'
    depends_on:
    - hub
    environment:
    - SE_EVENT_BUS_HOST=hub    #So here we need to put environment variable as it is required so that chrome container can talk with hub     
    - SE_EVENT_BUS_PUBLISH_PORT=4442   #ALL THIS INFORMATION IS PRESENT ON SELENIUM GRID OFFICIAL PAGE
    - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    - SE_NODE_OVERRIDE_MAX_SESSIONS=true   #this will increase the concurrency of each container
    - SE_NODE_MAX_SESSIONS=4   #this means the concurrency of each chrome container will be 4 now
    - SE_VNC_NO_PASSWORD=1    #this is used to see what is happeing inside the container by entering without any password
  firefox:
    image: selenium/node-firefox:4.10
    shm_size: '2g'
    depends_on:
    - hub
    environment:
    - SE_EVENT_BUS_HOST=hub    
    - SE_EVENT_BUS_PUBLISH_PORT=4442  #This publish port is used to register the node om this port with the hub
    - SE_EVENT_BUS_SUBSCRIBE_PORT=4443 #This subscribe port is used to get the information from the hub
    - SE_NODE_OVERRIDE_MAX_SESSIONS=true
    - SE_NODE_MAX_SESSIONS=4
    - SE_VNC_NO_PASSWORD=1

