pipeline{

      agent any

      stages{

          stage('Build JAR'){
                agent{
                    docker{
                      image 'maven:3.9.3-eclipse-temurin-17-focal'
                      args '-u root -v /tmp/m2:/root/.m2'
                    }
                }

              }
              steps{
                     bat "mvn clean package -DskipTests"
              }

          }
           stage('Build Image'){
                steps{
                   script{
                     app=docker.build('shaarv70/selenium')
               }
           }
         }
            stage('Push Image'){
                steps{
                   script{
                       docker.withRegistry('','dockerhub-creds'){
                        app.push("latest")
                       }
                   }
               }

            }

       }
   }
